[project]
name = "robertsrules"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.5",
    "pandas>=2.3.2",
    "pandas-stubs==2.3.2.250827",
    "scikit-learn>=1.7.1",
    "statsmodels>=0.14.5",
]
